name: flutter_translate_preferences
description: A flutter_translate extension for automatically saving &amp; restoring the selected locale.
version: 1.1.0+1
author: Florin Bratan <florin@leadcode.io>
homepage: https://github.com/bratan/flutter_translate

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.3+5
  flutter_translate: ^1.4.0+2

flutter:
