name: flutter_translate_community
description: Flutter Translate is a fully featured localization / internationalization (i18n) library for Flutter (community translation fork).
version: 4.0.3
repository: https://github.com/guillaumeboehm/Flutter-Translate

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  universal_io: ^2.0.4
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
