name: flutter_translate
description: Flutter Translate is a fully featured localization / internationalization (i18n) library for Flutter.
version: 5.0.0-dev.1
homepage: https://jesway.com
repository: https://github.com/Jesway/flutter_translate
topics:
  - localization
  - i18n
  - translation
  - internationalization
  - globalization
  - flutter
  - jesway

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: '>=0.17.0-0 <=0.18.1'
  shared_preferences: ^2.2.2
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter: