name: flutter_translate
description: Flutter Translate is a fully featured localization / internationalization (i18n) library for Flutter.
version: 1.6.0
homepage: https://leadcode.dev
repository: https://github.com/bratan/flutter_translate

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_device_locale: ^0.4.0

dev_dependencies:
  build_runner: ^1.10.1
  pedantic: ^1.9.2

flutter:
